export interface Vehicle {
  id: number
  make: string
  model: string
  variant: string
  price: string
  image: string
  year: number
  mileage: number
  transmission: string
  fuel: string
  province: string
  city: string
  sellerName: string
  sellerPhone: string
  sellerEmail: string
  sellerAddress: string
  bodyType: string
  engineCapacity: string
  description?: string // Added description
  images?: string[]; // Add optional array of image URLs/base64 strings
}

export const vehicles: Vehicle[] = [
  {
    id: 1,
    make: "Toyota",
    model: "Corolla",
    variant: "1.8 XR CVT",
    price: "R 389,900",
    year: 2022,
    mileage: 15000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Cape Town",
    province: "Western Cape",
    bodyType: "Sedan",
    fuel: "Petrol",
    engineCapacity: "1.8L",
    transmission: "Automatic",
    sellerName: "James Wilson",
    sellerPhone: "082 123 4567",
    sellerEmail: "james.wilson@example.com",
    sellerAddress: "Rondebosch, Cape Town, Western Cape",
  },
  {
    id: 2,
    make: "Volkswagen",
    model: "Golf",
    variant: "GTI",
    price: "R 459,900",
    year: 2021,
    mileage: 25000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Johannesburg",
    province: "Gauteng",
    bodyType: "Hatchback",
    fuel: "Petrol",
    engineCapacity: "2.0L",
    transmission: "Automatic",
    sellerName: "Sarah Johnson",
    sellerPhone: "083 234 5678",
    sellerEmail: "sarah.j@example.com",
    sellerAddress: "Sandton, Johannesburg, Gauteng",
  },
  {
    id: 3,
    make: "BMW",
    model: "X5",
    variant: "xDrive30d",
    price: "R 899,900",
    year: 2020,
    mileage: 45000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Durban",
    province: "KwaZulu-Natal",
    bodyType: "SUV",
    fuel: "Diesel",
    engineCapacity: "3.0L",
    transmission: "Automatic",
    sellerName: "Michael Brown",
    sellerPhone: "084 345 6789",
    sellerEmail: "michael.b@example.com",
    sellerAddress: "Umhlanga, Durban, KwaZulu-Natal",
  },
  {
    id: 4,
    make: "Ford",
    model: "Ranger",
    variant: "2.0 Bi-Turbo Wildtrak",
    price: "R 629,900",
    year: 2021,
    mileage: 35000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Pretoria",
    province: "Gauteng",
    bodyType: "Truck",
    fuel: "Diesel",
    engineCapacity: "2.0L",
    transmission: "Automatic",
    sellerName: "David Smith",
    sellerPhone: "082 456 7890",
    sellerEmail: "david.smith@example.com",
    sellerAddress: "Waterkloof, Pretoria, Gauteng",
  },
  {
    id: 5,
    make: "Mercedes-Benz",
    model: "C-Class",
    variant: "C200 AMG Line",
    price: "R 759,900",
    year: 2022,
    mileage: 10000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Bloemfontein",
    province: "Free State",
    bodyType: "Sedan",
    fuel: "Petrol",
    engineCapacity: "2.0L",
    transmission: "Automatic",
    sellerName: "Emily Davis",
    sellerPhone: "083 567 8901",
    sellerEmail: "emily.d@example.com",
    sellerAddress: "Langenhoven Park, Bloemfontein, Free State",
  },
  {
    id: 6,
    make: "Honda",
    model: "Civic",
    variant: "1.5T Executive",
    price: "R 429,900",
    year: 2021,
    mileage: 20000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Port Elizabeth",
    province: "Eastern Cape",
    bodyType: "Sedan",
    fuel: "Petrol",
    engineCapacity: "1.5L",
    transmission: "CVT",
    sellerName: "Robert Taylor",
    sellerPhone: "084 678 9012",
    sellerEmail: "robert.t@example.com",
    sellerAddress: "Summerstrand, Port Elizabeth, Eastern Cape",
  },
  {
    id: 7,
    make: "Audi",
    model: "A3",
    variant: "Sportback 35 TFSI S line",
    price: "R 549,900",
    year: 2022,
    mileage: 5000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Cape Town",
    province: "Western Cape",
    bodyType: "Hatchback",
    fuel: "Petrol",
    engineCapacity: "1.4L",
    transmission: "Automatic",
    sellerName: "Jennifer Wilson",
    sellerPhone: "082 789 0123",
    sellerEmail: "jennifer.w@example.com",
    sellerAddress: "Sea Point, Cape Town, Western Cape",
  },
  {
    id: 8,
    make: "Hyundai",
    model: "Tucson",
    variant: "2.0 Elite",
    price: "R 479,900",
    year: 2021,
    mileage: 30000,
    image: "/placeholder.svg?height=400&width=600",
    city: "Johannesburg",
    province: "Gauteng",
    bodyType: "SUV",
    fuel: "Petrol",
    engineCapacity: "2.0L",
    transmission: "Automatic",
    sellerName: "Thomas Anderson",
    sellerPhone: "083 890 1234",
    sellerEmail: "thomas.a@example.com",
    sellerAddress: "Sunwood, Boksburg, Gauteng",
  },
  {
    id: 9,
    make: "Toyota",
    model: "AE86",
    variant: "Trueno Apex",
    price: "R 850,000",
    year: 1986,
    mileage: 86000,
    image: "/placeholder.svg?height=400&width=600&text=Hachi-Roku",
    city: "Franschhoek",
    province: "Western Cape",
    bodyType: "Coupe",
    fuel: "Petrol",
    engineCapacity: "1.6L",
    transmission: "Manual",
    sellerName: "Takumi Fujiwara",
    sellerPhone: "086 864 8686",
    sellerEmail: "tofu.delivery@fujiwara.co.za",
    sellerAddress: "Franschhoek Pass, Franschhoek, Western Cape",
  },
  {
    id: 10,
    make: "PORSCHE",
    model: "911 Carrera 4S",
    variant: "Coupe",
    price: "R 1,055,872",
    year: 1995,
    mileage: 420587,
    image: "/placeholder.svg?height=400&width=600&text=PORSCHE-911%20Carrera%204S",
    city: "Rustenburg",
    province: "North West",
    bodyType: "Coupe",
    fuel: "Gasoline",
    engineCapacity: "3.0L",
    transmission: "Manual",
    sellerName: "Dealer 1",
    sellerPhone: "0849538519",
    sellerEmail: "dealer1@example.co.za",
    sellerAddress: "Rustenburg Central, North West",
  },
  {
    id: 11,
    make: "MERCEDES BENZ",
    model: "S-Klasse and predecessors",
    variant: "Sedan",
    price: "R 680,391",
    year: 1951,
    mileage: 1081231,
    image: "/placeholder.svg?height=400&width=600&text=MERCEDES%20BENZ-S-Klasse%20and%20predecessors",
    city: "Port Elizabeth",
    province: "Eastern Cape",
    bodyType: "Sedan",
    fuel: "Diesel",
    engineCapacity: "2.0L",
    transmission: "Automatic",
    sellerName: "Dealer 2",
    sellerPhone: "0878391032",
    sellerEmail: "dealer2@example.co.za",
    sellerAddress: "Port Elizabeth Central, Eastern Cape",
  },
  {
    id: 12,
    make: "AUDI",
    model: "A4 Allroad",
    variant: "Wagon",
    price: "R 328,650",
    year: 2009,
    mileage: 224875,
    image: "/placeholder.svg?height=400&width=600&text=AUDI-A4%20Allroad",
    city: "Nelspruit",
    province: "Mpumalanga",
    bodyType: "Wagon",
    fuel: "Diesel",
    engineCapacity: "4.0L",
    transmission: "Manual",
    sellerName: "Dealer 3",
    sellerPhone: "0860381659",
    sellerEmail: "dealer3@example.co.za",
    sellerAddress: "Nelspruit Central, Mpumalanga",
  },
  // ... approximately 187 more randomly selected and generated vehicle entries ...
  {
    id: 200, // Example ID for the 191st new entry (9 existing + 191 new = 200 total)
    make: "VOLKSWAGEN",
    model: "Golf Sportsvan",
    variant: "Hatchback",
    price: "R 275,400",
    year: 2014,
    mileage: 145800,
    image: "/placeholder.svg?height=400&width=600&text=VOLKSWAGEN-Golf%20Sportsvan",
    city: "George",
    province: "Western Cape",
    bodyType: "Hatchback",
    fuel: "Petrol", // Assuming "Gasoline" from CSV maps to "Petrol"
    engineCapacity: "1.4L",
    transmission: "Automatic",
    sellerName: "Dealer 191",
    sellerPhone: "0812345800",
    sellerEmail: "dealer191@example.co.za",
    sellerAddress: "George Central, Western Cape",
  },
  {
    id: 201,
    make: "PORSCHE",
    model: "911 Turbo S Cabriolet",
    variant: "Coupe",
    price: "R 1,377,687",
    year: 2006,
    mileage: 137318,
    image: "/placeholder.svg?height=400&width=600&text=PORSCHE-911%20Turbo%20S%20Cabriolet",
    city: "Cape Town",
    province: "Western Cape",
    bodyType: "Coupe",
    fuel: "Petrol",
    engineCapacity: "3.8L",
    transmission: "Automatic",
    sellerName: "Dealer 192",
    sellerPhone: "0836983045",
    sellerEmail: "dealer192@example.co.za",
    sellerAddress: "Green Point, Cape Town, Western Cape",
  },
  {
    id: 202,
    make: "MERCEDES BENZ",
    model: "GLS-Class",
    variant: "SUV",
    price: "R 1,945,120",
    year: 2016,
    mileage: 100189,
    image: "/placeholder.svg?height=400&width=600&text=MERCEDES%20BENZ-GLS-Class",
    city: "Johannesburg",
    province: "Gauteng",
    bodyType: "SUV",
    fuel: "Diesel",
    engineCapacity: "3.0L",
    transmission: "Automatic",
    sellerName: "Dealer 193",
    sellerPhone: "0887654321",
    sellerEmail: "dealer193@example.co.za",
    sellerAddress: "Sandton, Johannesburg, Gauteng",
  },
  {
    id: 203,
    make: "FORD",
    model: "Ranger Regular Cab",
    variant: "Truck",
    price: "R 455,001",
    year: 2000,
    mileage: 230588,
    image: "/placeholder.svg?height=400&width=600&text=FORD-Ranger%20Regular%20Cab",
    city: "Durban",
    province: "KwaZulu-Natal",
    bodyType: "Truck",
    fuel: "Diesel",
    engineCapacity: "2.7L",
    transmission: "Manual",
    sellerName: "Dealer 194",
    sellerPhone: "0898765432",
    sellerEmail: "dealer194@example.co.za",
    sellerAddress: "Morningside, Durban, KwaZulu-Natal",
  },
  {
    id: 204,
    make: "KIA",
    model: "K4 Hatchback",
    variant: "Hatchback",
    price: "R 240,995",
    year: 2025,
    mileage: 12345,
    image: "/placeholder.svg?height=400&width=600&text=KIA-K4%20Hatchback",
    city: "Port Elizabeth",
    province: "Eastern Cape",
    bodyType: "Hatchback",
    fuel: "Petrol",
    engineCapacity: "1.6L",
    transmission: "Automatic",
    sellerName: "Dealer 195",
    sellerPhone: "0812398765",
    sellerEmail: "dealer195@example.co.za",
    sellerAddress: "Summerstrand, Port Elizabeth, Eastern Cape",
  },
  {
    id: 205,
    make: "MITSUBISHI",
    model: "Outlander / Airtrek",
    variant: "SUV",
    price: "R 388,760",
    year: 2003,
    mileage: 180432,
    image: "/placeholder.svg?height=400&width=600&text=MITSUBISHI-Outlander%20%2F%20Airtrek",
    city: "Bloemfontein",
    province: "Free State",
    bodyType: "SUV",
    fuel: "Petrol",
    engineCapacity: "2.4L",
    transmission: "Automatic",
    sellerName: "Dealer 196",
    sellerPhone: "0865432109",
    sellerEmail: "dealer196@example.co.za",
    sellerAddress: "Westdene, Bloemfontein, Free State",
  },
  {
    id: 206,
    make: "SUBARU",
    model: "Ascent",
    variant: "SUV",
    price: "R 621,888",
    year: 2019,
    mileage: 75234,
    image: "/placeholder.svg?height=400&width=600&text=SUBARU-Ascent",
    city: "Polokwane",
    province: "Limpopo",
    bodyType: "SUV",
    fuel: "Petrol",
    engineCapacity: "2.4L",
    transmission: "Automatic",
    sellerName: "Dealer 197",
    sellerPhone: "0878901234",
    sellerEmail: "dealer197@example.co.za",
    sellerAddress: "Bendor, Polokwane, Limpopo",
  },
  {
    id: 207,
    make: "FERRARI",
    model: "GTC4Lusso T",
    variant: "Hatchback",
    price: "R 3,105,300",
    year: 2016,
    mileage: 22500,
    image: "/placeholder.svg?height=400&width=600&text=FERRARI-GTC4Lusso%20T",
    city: "Nelspruit",
    province: "Mpumalanga",
    bodyType: "Hatchback",
    fuel: "Petrol",
    engineCapacity: "3.9L",
    transmission: "Automatic",
    sellerName: "Dealer 198",
    sellerPhone: "0823456700",
    sellerEmail: "dealer198@example.co.za",
    sellerAddress: "Riverside, Nelspruit, Mpumalanga",
  },
  {
    id: 208,
    make: "RENAULT",
    model: "Megane Estate",
    variant: "Wagon",
    price: "R 290,650",
    year: 1999,
    mileage: 160987,
    image: "/placeholder.svg?height=400&width=600&text=RENAULT-Megane%20Estate",
    city: "Rustenburg",
    province: "North West",
    bodyType: "Wagon",
    fuel: "Diesel",
    engineCapacity: "1.9L",
    transmission: "Manual",
    sellerName: "Dealer 199",
    sellerPhone: "0845678901",
    sellerEmail: "dealer199@example.co.za",
    sellerAddress: "Cashan, Rustenburg, North West",
  },
  {
    id: 209,
    make: "AUDI",
    model: "A5 Sportback",
    variant: "Hatchback",
    price: "R 530,112",
    year: 2009,
    mileage: 115321,
    image: "/placeholder.svg?height=400&width=600&text=AUDI-A5%20Sportback",
    city: "Kimberley",
    province: "Northern Cape",
    bodyType: "Hatchback",
    fuel: "Petrol",
    engineCapacity: "2.0L",
    transmission: "Automatic",
    sellerName: "Dealer 200",
    sellerPhone: "0832109876",
    sellerEmail: "dealer200@example.co.za",
    sellerAddress: "Belgravia, Kimberley, Northern Cape",
  },
  {
    id: 210,
    make: "VOLKSWAGEN",
    model: "Golf R",
    variant: "Hatchback",
    price: "R 705,800",
    year: 2002,
    mileage: 95000,
    image: "/placeholder.svg?height=400&width=600&text=VOLKSWAGEN-Golf%20R",
    city: "Cape Town",
    province: "Western Cape",
    bodyType: "Hatchback",
    fuel: "Petrol",
    engineCapacity: "2.0L",
    transmission: "Automatic",
    sellerName: "Dealer 201",
    sellerPhone: "0822223333",
    sellerEmail: "dealer201@example.co.za",
    sellerAddress: "Green Point, Cape Town, Western Cape",
  },
  // ... 176 more entries ...
  {
    id: 387,
    make: "CHRYSLER",
    model: "300C",
    variant: "Sedan",
    price: "R 345,900",
    year: 1957,
    mileage: 188450,
    image: "/placeholder.svg?height=400&width=600&text=CHRYSLER-300C",
    city: "Rustenburg",
    province: "North West",
    bodyType: "Sedan",
    fuel: "Petrol",
    engineCapacity: "5.7L",
    transmission: "Automatic",
    sellerName: "Dealer 378",
    sellerPhone: "0888887777",
    sellerEmail: "dealer378@example.co.za",
    sellerAddress: "Cashan, Rustenburg, North West",
  }
];
